# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 08:08
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='工位分机号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job_num',
            field=models.CharField(help_text='请填写工号，型如：z18861', max_length=30, unique=True, verbose_name='工号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(help_text='请输入您的名字', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='用户名'),
        ),
    ]
