# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 00:51
from __future__ import unicode_literals

import backend.apps.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171017_1608'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', backend.apps.users.models.MyUserManager()),
            ],
        ),
    ]
