# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171018_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='', upload_to='avatar', verbose_name='头像'),
        ),
    ]
