# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 01:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('department', models.CharField(max_length=30, verbose_name='设备归属部门')),
                ('port', models.IntegerField(verbose_name='交换机连接端口')),
                ('unit_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='型号及其他')),
                ('version', models.CharField(blank=True, max_length=20, null=True, verbose_name='使用版本')),
                ('setup_time', models.DateField(default=datetime.datetime.now, verbose_name='搭建时间')),
                ('principal', models.CharField(max_length=20, verbose_name='环境负责人')),
                ('dbs_type', models.IntegerField(choices=[(2, 'Oracle'), (1, 'MySQL')], verbose_name='数据库类型')),
            ],
            options={
                'verbose_name': 'DBS',
                'verbose_name_plural': 'DBS',
            },
        ),
        migrations.CreateModel(
            name='MSO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mso_id', models.CharField(max_length=20, verbose_name='中控id')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('department', models.CharField(max_length=30, verbose_name='设备归属部门')),
                ('port', models.IntegerField(verbose_name='交换机连接端口')),
                ('unit_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='型号及其他')),
                ('version', models.CharField(blank=True, max_length=20, null=True, verbose_name='使用版本')),
                ('setup_time', models.DateField(default=datetime.datetime.now, verbose_name='搭建时间')),
                ('principal', models.CharField(max_length=20, verbose_name='环境负责人')),
            ],
            options={
                'verbose_name': 'MSO',
                'verbose_name_plural': 'MSO',
            },
        ),
        migrations.CreateModel(
            name='TSC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsc_id', models.CharField(max_length=20, verbose_name='基站id')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('department', models.CharField(max_length=30, verbose_name='设备归属部门')),
                ('port', models.IntegerField(verbose_name='交换机连接端口')),
                ('carrier_num', models.IntegerField(verbose_name='载频数')),
                ('unit_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='型号及其他')),
                ('version', models.CharField(blank=True, max_length=20, null=True, verbose_name='使用版本')),
                ('setup_time', models.DateField(default=datetime.datetime.now, verbose_name='搭建时间')),
                ('principal', models.CharField(max_length=20, verbose_name='环境负责人')),
                ('tsc_type', models.IntegerField(choices=[(1, 'Large Clusters'), (2, 'Small Clusters')], verbose_name='集群类型')),
                ('mso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='have_tsc', to='tsc.MSO', verbose_name='归属的中控')),
            ],
            options={
                'verbose_name': 'MSO',
                'verbose_name_plural': 'MSO',
            },
        ),
        migrations.AddField(
            model_name='dbs',
            name='mso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='have_dbs', to='tsc.MSO', verbose_name='归属的中控'),
        ),
    ]
