# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsc', '0006_auto_20171012_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbs',
            name='dbs_type',
            field=models.IntegerField(choices=[(1, 'MySQL'), (2, 'Oracle')], verbose_name='数据库类型'),
        ),
    ]
