# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 00:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reminder',
        ),
        migrations.AddField(
            model_name='message',
            name='reminder',
            field=models.ManyToManyField(related_name='remind_messages', to=settings.AUTH_USER_MODEL, verbose_name='重点提醒人'),
        ),
    ]
