# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20171018_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='reminder',
            new_name='reminders',
        ),
    ]
